# Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: pass
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: shopapp

# Server Config
CONTAINER_PORT: 8090
ACTIVE_PROFILE: test

UI_APP_URL: http://localhost:4200

JWT_SECRET: 6A576D5A7134743777217A25432A462D4A614E645267556B5870327235753878

